version: "3.8"

services:
  traefik:
    image: traefik:v2.10.4
    ports:
      # Exposes port 80 for incomming web requests
      - 80:80
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/traefik/conf/traefik.yml:/etc/traefik/traefik.yml

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`$JENKINS_DNS`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
  
  ssh-agent:
    image: jenkins/ssh-agent

  sonarqube:
    image: sonarqube:lts-community
    restart: unless-stopped
    environment: 
      - "SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=$SONAR_ES_BOOTSTRAP_CHECKS_DISABLE"
      - "SONAR_TELEMETRY_ENABLE=$SONAR_TELEMETRY_ENABLE"
    volumes: 
      - sonarqube:/opt/sonarqube
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarqube.rule=Host(`$SONARQUBE_DNS`)"
      - "traefik.http.routers.sonarqube.entrypoints=web"
      - "traefik.http.routers.sonarqube.service=sonarqube"
      - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
  
  gitlab:
    image: gitlab/gitlab-ce
    environment:
      - "GITLAB_OMNIBUS_CONFIG=$GITLAB_OMNIBUS_CONFIG"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`$GITLAB_DNS`)"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.http.routers.gitlab.service=gitlab"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: 256m

volumes:
  jenkins_home:
  sonarqube:
  gitlab_config:
  gitlab_logs:
  gitlab_data: